### PR TITLE
T/4: The position of the floating toolbar should be updated after the editable has grown.

### LINKED ISSUE #4: The position of the floating toolbar is not updated after the editable grew
mar-09-2017 11-18-51

### PR DESCRIPTION
**Pull request by oleq**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Fix: The position of the floating toolbar should be updated after the editable has grown. Closes #4.

---

### Additional information

Requires https://github.com/ckeditor/ckeditor5-ui/pull/197.

### CODE REVIEW

**Comment by oskarwrobel** [comment]
Missing 100% CC.

**Comment by oskarwrobel** [comment]
Besides everything looks 👌

**Comment by oleq** [comment]
Fixed and done some refactoring. Please check it out.

**Comment by oleq** [comment]
PS. Don't forget about https://github.com/ckeditor/ckeditor5-image/pull/93 and https://github.com/ckeditor/ckeditor5-theme-lark/pull/85.

**Pull request merged**
